name: data_filter
description: Implement a one-dimensional data filter

homepage: https://github.com/leech001/data_filter
repository: https://github.com/leech001/data_filter/tree/main
issue_tracker: https://github.com/leech001/data_filter/issues
documentation: https://github.com/leech001/data_filter/blob/main/README.md

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.21.2
  test: ^1.21.6
